### ISSUE TITLE
Wc issue

### ISSUE THREAD

**Issue by su8** [ammongit/minutils#28]
Hello,

WC.c doesn't handle lines longer than 4095 chars, you should allocate memory, read the entire file content in the allocated array, split the content by the newline character and count the tokens instead using buffer that is to small and can skip longer lines.

**Comment by su8** [comment]
Have a look https://github.com/su8/iu-coreutils/blob/master/tac.c to get the idea how to do it.

**Comment by emmiegit** [comment]
Based on my testing, it works fine on lines longer than 4095 bytes.

I don't really see the need in storing the entire file: we're only counting data, so we can just read in small chunks and increment numbers instead of storing a potentially huge file in memory.
