### ISSUE TITLE
Assignment from incompatible pointer

### ISSUE THREAD

**Issue by su8** [ammongit/minutils#33]
https://github.com/ammongit/minutils/blob/30d832a500ccece3be45d9ca9d88b16eea2c1d9a/src/nl.c#L29

Can you crash the program when no arguments are given to it ?

**Comment by su8** [comment]
Same issue with sort.c

**Comment by emmiegit** [comment]
Fixed on the `bsd` branch

**Comment by su8** [comment]
@ammongit sort.c still suffers from this issue.

**Comment by su8** [comment]
Also it would be great to follow the patched OpenBSD gcc compiler suggestions: ![2017-12-24-235548_595x93_scrot](https://user-images.githubusercontent.com/29376083/34329386-b6117b2a-e906-11e7-87e4-bc6a305edca2.png)

![2017-12-25-000645_478x56_scrot](https://user-images.githubusercontent.com/29376083/34329426-46ad8286-e908-11e7-9e6d-799604413cc9.png)

**Comment by su8** [comment]
The same compiler doesn't understand `-Wno-implicit-fallthrough` https://github.com/ammongit/minutils/blob/a4b2499c671a731c3c713a01c6f09ec04e0c672a/Makefile#L44 , while the ordinary gcc and clang understand it.

**Comment by su8** [comment]
Perhaps there should be a check and assign this flag on systems other than OpenBSD like this:

```bash
	UNAME_S := $(shell uname -s)
	ifneq (,$(filter $(UNAME_S),Linux FreeBSD NetBSD DragonFly))
```
